modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU LGPL v3"

[[mods]]
modId = "obscraft"
version = "${version}"
displayName = "OBSCraft"
authors = "MoSadie"
description = '''
Communicate with the OBS WebSocket plugin to control OBS from within Minecraft.
'''
logoFile = "assets/obscraft/icon.png"

[[dependencies.obscraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obscraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obscraft]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "obscraft.mixins.json"
