modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU LGPL v3"

[[mods]]
modId = "obswscraft"
version = "${version}"
displayName = "OBSWScraft"
authors = "MoSadie"
description = '''
Communicate with the OBS WebSocket plugin to control OBS from within Minecraft.
'''
logoFile = "assets/obswscraft/icon.png"

[[dependencies.obswscraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obswscraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obswscraft]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "streamercraft.mixins.json"
